#pragma once
static const char INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang='es'>\n"
"<head>\n"
"<meta charset='UTF-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"<title>Robot Seguidor</title>\n"
"<style>\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{background:#0f172a;color:#e2e8f0;font-family:monospace;min-height:100vh}\n"
"header{display:flex;justify-content:space-between;align-items:center;padding:10px 16px;background:#1e293b;border-bottom:2px solid #3b82f6}\n"
"h1{font-size:13px;letter-spacing:2px;color:#3b82f6}\n"
".dot{width:9px;height:9px;border-radius:50%;background:#ef4444;display:inline-block;margin-right:5px;transition:background .3s}\n"
".dot.on{background:#22c55e}\n"
".conn{display:flex;gap:6px;padding:8px 16px;background:#1e293b;border-bottom:1px solid #334155;align-items:center;flex-wrap:wrap}\n"
".conn label{font-size:11px;color:#64748b}\n"
".conn input{flex:1;min-width:160px;padding:4px 7px;background:#0f172a;border:1px solid #475569;color:#e2e8f0;border-radius:4px;font-family:monospace;font-size:12px}\n"
".btn{padding:4px 10px;border:none;border-radius:4px;cursor:pointer;font-size:12px;font-family:monospace}\n"
".bb{background:#3b82f6;color:#fff}.br{background:#ef4444;color:#fff}.bg{background:#22c55e;color:#0f172a}.bs{background:#334155;color:#94a3b8}\n"
".cards{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;padding:10px 16px}\n"
"@media(max-width:500px){.cards{grid-template-columns:repeat(2,1fr)}}\n"
".card{background:#1e293b;border-radius:7px;padding:8px;text-align:center;border:1px solid #334155}\n"
".lbl{font-size:9px;color:#64748b;text-transform:uppercase;letter-spacing:1px;margin-bottom:3px}\n"
".val{font-size:18px;font-weight:bold}\n"
".badge{padding:2px 8px;border-radius:99px;font-size:10px;font-weight:bold}\n"
".bon{background:#14532d;color:#86efac}.boff{background:#450a0a;color:#fca5a5}\n"
".sec{font-size:10px;color:#475569;text-transform:uppercase;letter-spacing:2px;padding:6px 16px 3px}\n"
".sbars{display:flex;gap:3px;padding:0 16px 4px;height:48px;align-items:flex-end}\n"
".sbar{flex:1;background:#1e293b;border-radius:3px;border:1px solid #334155;overflow:hidden;display:flex;flex-direction:column-reverse}\n"
".sfill{background:#3b82f6;transition:height .1s;border-radius:2px}\n"
".sfill.act{background:#22c55e}\n"
".snums{display:flex;gap:3px;padding:0 16px 10px}\n"
".snum{flex:1;text-align:center;font-size:8px;color:#475569}\n"
".pbox{background:#1e293b;border:1px solid #334155;border-radius:7px;padding:12px;margin:0 16px 10px}\n"
".ptit{font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:1px;margin-bottom:10px;display:flex;align-items:center;gap:8px}\n"
".pgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}\n"
"@media(max-width:500px){.pgrid{grid-template-columns:repeat(2,1fr)}}\n"
".prow{display:flex;flex-direction:column;gap:3px}\n"
".prow label{font-size:9px;color:#94a3b8;letter-spacing:1px}\n"
".prow input[type=number]{width:100%;padding:4px 5px;background:#0f172a;border:1px solid #475569;color:#e2e8f0;border-radius:4px;font-family:monospace;font-size:13px;text-align:center}\n"
".prow input[type=range]{width:100%;accent-color:#3b82f6;margin-top:2px}\n"
".pact{display:flex;gap:6px;margin-top:10px;align-items:center}\n"
"#psaved{font-size:10px;color:#22c55e;transition:opacity .5s}\n"
".charts{display:grid;grid-template-columns:1fr 1fr;gap:6px;padding:0 16px 16px}\n"
"@media(max-width:600px){.charts{grid-template-columns:1fr}}\n"
".cbox{background:#1e293b;border-radius:7px;padding:10px;border:1px solid #334155}\n"
".cbox h3{font-size:9px;color:#64748b;text-transform:uppercase;letter-spacing:1px;margin-bottom:6px}\n"
"canvas{display:block;width:100%;border-radius:3px}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"<h1>ROBOT SEGUIDOR</h1>\n"
"<span><span class='dot' id='dot'></span><span id='stxt' style='font-size:11px;color:#94a3b8'>Desconectado</span></span>\n"
"</header>\n"
"<div class='conn'>\n"
"<label>WS:</label>\n"
"<input id='wsurl' value='ws://192.168.4.1/ws'>\n"
"<button class='btn bb' onclick='wsCon()'>Conectar</button>\n"
"<button class='btn br' onclick='wsDis()'>Desconectar</button>\n"
"</div>\n"
"<div class='cards'>\n"
"<div class='card'><div class='lbl'>Error</div><div class='val' id='verr'>-</div></div>\n"
"<div class='card'><div class='lbl'>Posicion</div><div class='val' id='vpos'>-</div></div>\n"
"<div class='card'><div class='lbl'>Vel Izq</div><div class='val' id='vlspd'>-</div></div>\n"
"<div class='card'><div class='lbl'>Vel Der</div><div class='val' id='vrspd'>-</div></div>\n"
"<div class='card'><div class='lbl'>Correccion</div><div class='val' id='vcorr'>-</div></div>\n"
"<div class='card'><div class='lbl'>Linea</div><div class='val' id='vline'>-</div></div>\n"
"<div class='card'><div class='lbl'>Motores</div><div class='val' id='vmot'>-</div></div>\n"
"<div class='card'><div class='lbl'>Start</div><div class='val' id='vstart'>-</div></div>\n"
"</div>\n"
"<div class='sec'>Sensores QTR-8</div>\n"
"<div class='sbars' id='sbars'></div>\n"
"<div class='snums' id='snums'></div>\n"
"<div class='pbox'>\n"
"<div class='ptit'>Parametros PID<span id='psaved' style='opacity:0'>Guardado</span></div>\n"
"<div class='pgrid'>\n"
"<div class='prow'><label>KP</label><input type='number' id='pkp' min='0' max='1' step='0.01' value='0.15'><input type='range' id='skp' min='0' max='1' step='0.01' value='0.15'></div>\n"
"<div class='prow'><label>KI</label><input type='number' id='pki' min='0' max='0.5' step='0.005' value='0.05'><input type='range' id='ski' min='0' max='0.5' step='0.005' value='0.05'></div>\n"
"<div class='prow'><label>KD</label><input type='number' id='pkd' min='0' max='0.05' step='0.001' value='0.001'><input type='range' id='skd' min='0' max='0.05' step='0.001' value='0.001'></div>\n"
"<div class='prow'><label>Vel Base</label><input type='number' id='pspd' min='0' max='255' step='1' value='140'><input type='range' id='sspd' min='0' max='255' step='1' value='140'></div>\n"
"</div>\n"
"<div class='pact'>\n"
"<button class='btn bg' onclick='applyParams()'>Aplicar</button>\n"
"<button class='btn bs' onclick='resetParams()'>Restablecer</button>\n"
"</div>\n"
"</div>\n"
"<div class='charts'>\n"
"<div class='cbox'><h3>Error / Correccion</h3><canvas id='cerr'></canvas></div>\n"
"<div class='cbox'><h3>Velocidades</h3><canvas id='cspd'></canvas></div>\n"
"<div class='cbox'><h3>Posicion</h3><canvas id='cpos'></canvas></div>\n"
"<div class='cbox'><h3>Sensores Activos</h3><canvas id='csens'></canvas></div>\n"
"</div>\n"
"<script>\n"
"var NS=8,WIN=120,DEFS={kp:.15,ki:.05,kd:.001,speed:140};\n"
"var sb=document.getElementById('sbars'),sn=document.getElementById('snums');\n"
"for(var i=0;i<NS;i++){\n"
"var b=document.createElement('div');b.className='sbar';\n"
"b.innerHTML='<div class=\"sfill\" id=\"sf'+i+'\" style=\"height:0%\"></div>';\n"
"sb.appendChild(b);\n"
"var n=document.createElement('div');n.className='snum';n.id='sn'+i;n.textContent='S'+i;\n"
"sn.appendChild(n);\n"
"}\n"
"['kp','ki','kd','spd'].forEach(function(id){\n"
"var p=document.getElementById('p'+id),s=document.getElementById('s'+id);\n"
"p.oninput=function(){s.value=p.value;};s.oninput=function(){p.value=s.value;};\n"
"});\n"
"function MkChart(id,ser,mn,mx){\n"
"var cv=document.getElementById(id),dat=ser.map(function(){return[];}),ctx=cv.getContext('2d');\n"
"function draw(){\n"
"var w=cv.parentElement.clientWidth-20,h=80;cv.width=w;cv.height=h;\n"
"ctx.fillStyle='#0f172a';ctx.fillRect(0,0,w,h);\n"
"ctx.strokeStyle='#1e3040';ctx.lineWidth=1;\n"
"for(var r=1;r<4;r++){ctx.beginPath();ctx.moveTo(0,h*r/4);ctx.lineTo(w,h*r/4);ctx.stroke();}\n"
"ser.forEach(function(s,si){\n"
"if(!dat[si].length)return;\n"
"ctx.strokeStyle=s[1];ctx.lineWidth=1.5;ctx.beginPath();\n"
"dat[si].forEach(function(v,i){\n"
"var x=w*i/(WIN-1),y=h-(v-mn)/(mx-mn)*h;\n"
"if(y<0)y=0;if(y>h)y=h;\n"
"i?ctx.lineTo(x,y):ctx.moveTo(x,y);\n"
"});ctx.stroke();\n"
"});}\n"
"return{push:function(){var a=arguments;ser.forEach(function(_,i){dat[i].push(+a[i]);if(dat[i].length>WIN)dat[i].shift();});draw();}};\n"
"}\n"
"var cE=MkChart('cerr',[['E','#ef4444'],['C','#f59e0b']],-3500,3500);\n"
"var cS=MkChart('cspd',[['I','#3b82f6'],['D','#22c55e']],0,255);\n"
"var cP=MkChart('cpos',[['P','#a855f7']],0,7000);\n"
"var cA=MkChart('csens',[['A','#06b6d4']],0,8);\n"
"function badge(v){return v?'<span class=\"badge bon\">SI</span>':'<span class=\"badge boff\">NO</span>';}\n"
"var pL=false;\n"
"function loadP(d){\n"
"if(pL||d.kp===undefined)return;\n"
"['kp','ki','kd'].forEach(function(k){document.getElementById('p'+k).value=d[k];document.getElementById('s'+k).value=d[k];});\n"
"document.getElementById('pspd').value=d.speed;document.getElementById('sspd').value=d.speed;\n"
"pL=true;\n"
"}\n"
"function onData(d){\n"
"document.getElementById('verr').textContent=d.err;\n"
"document.getElementById('vpos').textContent=d.pos;\n"
"document.getElementById('vlspd').textContent=d.lspd;\n"
"document.getElementById('vrspd').textContent=d.rspd;\n"
"document.getElementById('vcorr').textContent=d.corr.toFixed(1);\n"
"document.getElementById('vline').innerHTML=badge(d.line);\n"
"document.getElementById('vmot').innerHTML=badge(d.mot);\n"
"document.getElementById('vstart').innerHTML=badge(d.start);\n"
"var act=0;\n"
"d.sens.forEach(function(v,i){\n"
"var f=document.getElementById('sf'+i),n=document.getElementById('sn'+i);\n"
"f.style.height=(v/10)+'%';f.className='sfill'+(v>500?' act':'');n.textContent=v;\n"
"if(v>500)act++;\n"
"});\n"
"cE.push(d.err,d.corr);cS.push(d.lspd,d.rspd);cP.push(d.pos);cA.push(act);\n"
"loadP(d);\n"
"}\n"
"function applyParams(){\n"
"if(!ws||ws.readyState!==1){alert('Sin conexion');return;}\n"
"ws.send(JSON.stringify({cmd:'set',\n"
"kp:parseFloat(document.getElementById('pkp').value),\n"
"ki:parseFloat(document.getElementById('pki').value),\n"
"kd:parseFloat(document.getElementById('pkd').value),\n"
"speed:parseInt(document.getElementById('pspd').value)}));\n"
"var s=document.getElementById('psaved');s.style.opacity='1';setTimeout(function(){s.style.opacity='0';},2500);\n"
"}\n"
"function resetParams(){\n"
"document.getElementById('pkp').value=DEFS.kp;document.getElementById('skp').value=DEFS.kp;\n"
"document.getElementById('pki').value=DEFS.ki;document.getElementById('ski').value=DEFS.ki;\n"
"document.getElementById('pkd').value=DEFS.kd;document.getElementById('skd').value=DEFS.kd;\n"
"document.getElementById('pspd').value=DEFS.speed;document.getElementById('sspd').value=DEFS.speed;\n"
"applyParams();\n"
"}\n"
"var ws=null;\n"
"function wsCon(){\n"
"wsDis();pL=false;\n"
"var url=document.getElementById('wsurl').value.trim();\n"
"ws=new WebSocket(url);\n"
"ws.onopen=function(){document.getElementById('dot').classList.add('on');document.getElementById('stxt').textContent='Conectado';};\n"
"ws.onclose=ws.onerror=function(){document.getElementById('dot').classList.remove('on');document.getElementById('stxt').textContent='Desconectado';};\n"
"ws.onmessage=function(e){try{onData(JSON.parse(e.data));}catch(x){}};\n"
"}\n"
"function wsDis(){if(ws){ws.close();ws=null;}}\n"
"wsCon();\n"
"</script>\n"
"</body>\n"
"</html>\n"
;
